default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['BARBER_DB_USERNAME'] %>
  password: <%= ENV['BARBER_DB_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: <%= ENV['BARBER_DB_SCHEMA'] %>

test:
  <<: *default
  database: <%= ENV['BARBER_TEST_DB_SCHEMA'] %>

production:
  <<: *default
  database: barber_production
  username: barber
  password: <%= ENV['BARBER_DATABASE_PASSWORD'] %>
